### ISSUE TITLE
Inappropriate language

### ISSUE THREAD

**Issue by 0x5bjorn** [beksultantuleev/inertial_navigation#1]
There is a usage of bad words in README file. @beksultantuleev

**Comment by beksultantuleev** [comment]
Dear Sultan,

Thank you for the comment and I appreciate your meticulous approach. All bad words shall be removed in an immediate manner. Please let me know if you catch sight of any other issues. You can find me by commenting here or in the telegram group (1/2 semi-man + 1/2 man).

kind regards,
BT
